import { catchAsyncError } from "../middlewares/catchAsyncError.js";

export const getUser = catchAsyncError(async (req, res, next) => {
  const user = req.user;
  res.status(200).json({
    success: true,
    user,
  });
})